### PR TITLE
feat: added theme setting options - dark mode, palette

### PR DESCRIPTION
**Pull request by syntaxlexx**
## Summary

Added the config options for themes

## Issue

https://github.com/asantibanez/livewire-charts/issues/44
https://github.com/asantibanez/livewire-charts/issues/3

## Type of Change

- [ ] :rocket: New Feature
Added themes support
 - dark/light mode
 - palettes
Currently, apex charts have added options to swap themes
```js
theme: {
      mode: 'light', 
      palette: 'palette1', 
      monochrome: {
          enabled: false,
          color: '#255aee',
          shadeTo: 'light',
          shadeIntensity: 0.65
      },
  }
```
This PR sets the `theme.mode` and `theme.palette` options

## Screenshot/Video
image

image

image

[Provide a screenshot or video that describes the change if applicable]

### CODE REVIEW

**Comment by ajmeireles** [comment]
Hey! @asantibanez Do you have any expectations about when this PR will be merged?

**Comment by mbardelmeijer** [comment]
@asantibanez would love to see support for this as well. If there is anything I can do to help out let me know!

**Comment by phuclh** [comment]
@asantibanez any chances to merge this PR? Thank you!

**Comment by asantibanez** [comment]
Looks great @syntaxlexx. It's been a long wait for this to be merged in. 

Merging.

**Pull request merged**
