### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^10.5`. If you would like to also upgrade your tests, you may run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/livewire-charts.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "asantibanez/livewire-charts": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by mbardelmeijer** [comment]
@asantibanez would you mind taking a look here? :)

**Comment by mrdezzods** [comment]
Can this pr be merged?

**Comment by RohanSakhale** [comment]
@asantibanez can you please take a look at this PR

**Comment by gmorgas** [comment]
@asantibanez can this pr be merged? It's blocking us to upgrade to lLravel 11.

**Comment by reinschaap** [comment]
Would you please merge this PR? I need to upgrade some projects to Laravel 11 as well and we are waiting for this PR. Thank you

**Comment by santos-sabanari** [comment]
@asantibanez please merge this PR

**Comment by sjwatts119** [comment]
Please merge this!

**Comment by pboese** [comment]
@asantibanez would be awesome if you could merge this simple PR :-)

**Comment by ricuss** [comment]
@asantibanez Could you please merge this pr when you get a chance?

**Comment by nerijuso** [comment]
@asantibanez Could you please merge this pr?

**Comment by philipsorensen** [comment]
@asantibanez is there anything blocking this PR? Please let us know, if you need help. Would love to get Laravel 11 support.

**Comment by Kuzat** [comment]
@asantibanez Would be really nice if this PR could be merged 🙏

**Comment by davidsneal** [comment]
Bumping to get notifications if merged :)

**Comment by nedwors** [comment]
@asantibanez 

Thank you for the amazing package! As everyone has noted above, it would be awesome to see this merged.

If not for us, please consider doing it for these poor 47 tests:

image

It's not their fault! #WontSomeoneThinkOfTheFailingTests

Thanks! 😎

**Comment by RohanSakhale** [comment]
> ⚗️ **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.
> 
> To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:
> 
> ```json
> {
>     "repositories": [
>         {
>             "type": "vcs",
>             "url": "https://github.com/laravel-shift/livewire-charts.git"
>         }
>     ]
> }
> ```
> 
> Then update your dependency constraint to reference this branch:
> 
> ```json
> {
>     "require": {
>         "asantibanez/livewire-charts": "dev-l11-compatibility",
>     }
> }
> ```
> 
> Finally, run: `composer update`

We have been using this way for time being until I see it's merged

**Comment by asantibanez** [comment]
Hello everyone. Planning to release a new version today. Sorry for the long wait. 👍

**Pull request merged**
